---
apiVersion: v1
kind: Service
metadata:
  name: postgres-lb
  annotations:
    lbipam.cilium.io/ips: 10.10.5.204
spec:
  type: LoadBalancer
  ports:
    - name: postgres
      port: 5432
      protocol: TCP
      targetPort: 5432
  selector:
    cnpg.io/cluster: postgres
    cnpg.io/instanceRole: primary
