# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:4PyCbimkSVtd+G74GVNy4IIjmhiG5jQ2rYl6A8pTVI03ISgwY3HjjiCU4Rg6adEcQ8aXzyThUWC+5TjtX+CCcUfB0zvCZy5+CREck5YwPLGIJ2cXQccTPcD9l66q33er7wVIblbUBItU1z6KnXS5OauCMp1OJQ0dtXUeuaotgrXzQjdNiT0RLhp6sWlozeKlKuD56yCUe9F2l55zCfcl9RZ7JK3ejLO9OGKFMhLoqQ==,iv:VIeO1BeHqjEbJX3rwQ763AT9MPGXiRzwilpN5IgdVbk=,tag:lCvG3o5HPrLoTnuA1tdJjw==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m23ymejrcl6ngxw3szegd0y9jczamudr4wuw9ql77g5h72xk64qsm6zvmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBhOFloaTlTdFVBTk40WEQ1
        cHdFNE8rSjlUVXBieTlmZ2l4WEpzVkNsUEJNCk5IRGJNMG9hOHRxSDZJRUJNSXFL
        MW9hY2ZkSUdkSW5jd1F2RFlQTkNTNVEKLS0tIEFSdS9MSnBUS3dnK3QrZHJ3cklk
        V0JkWk1jeWIwMUVleXY5OThoQ2pwdFkKuYIoG4780cot08bZEdeP9Y1WiMhepyhq
        8Is5CkYP1ixD3rj0JWfArBZLdphM3y+Cb89MO5PYA61wSFVc9RHtOw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T19:37:30Z"
  mac: ENC[AES256_GCM,data:ZF54AJ+PzLiId9yaRFqe55dI1MqDI++jY3dqPdInoDY2TjtZ/k3ql8D+lrjrEsaCoWMWt5LQoBDbUCKhIHaHbDMtLtJBbiAkpxyaTl1ibbcj6H144URRLXQ/DpXThE7QvGnfo9IbH47jGjumnCEqK8EhbdX65yVx02Ys0p53418=,iv:vBlwAGVkjGcAxK0cU4bKH5IWjaf1qsGA1PfgjkRrB5s=,tag:lgBK1gCPzbXYzuR4cyAqjA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
