# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: cloudflared-secret
stringData:
  credentials.json: ENC[AES256_GCM,data:rhtZhuuouh04zgF5g5HfS7cbV9Bzec8g6oZ+UdO13S5sMmAxOTX+giBQhMqn3pDFUT34mZDCzctfrZ/wjHIm8zf/V2evwt8Ls7fMUKg3zi94DN0U8v77FlFs4W+G18iq1TR4hJTXVXhtaDlc1RMVpZs3CU98LcnpBECFDOcNlMeU12dAcQaPWr3o2rcd3xSE0AbYI9To8HW0vcl6boWgAX/5pog8tXj8J2W1LjUlcw==,iv:mfUyJIQcahhNg5p/Vz3KFKb7UjkVDAdSGQLnPjAfJyI=,tag:zKyUuAZuACrXJtnHR+MTxg==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m23ymejrcl6ngxw3szegd0y9jczamudr4wuw9ql77g5h72xk64qsm6zvmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBnSVNweGpSYU9ZaW52U0Nr
        K1cvZ05zbjNmTURzZGV2WDV1L3dseUk5d0R3CjVCdjY3OGR4MzczVFNROXoyRnBz
        d29hallIOFVwcC9CRjJ0TFFEM1FJZm8KLS0tIGVrWXJRODlvWUxFUy9JcnJla2Ux
        eGpualdaTldFdEdways1OU4wdll2azAKZolILde0WyQVxSuHnpmZxgIh6hD6rmk2
        y+sQfEH41lvmh3tEECVzIG0GJ/Dpz8e73by1y8+M6eXwO1vmDYnTgA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T17:57:53Z"
  mac: ENC[AES256_GCM,data:dyVRi6q/oLxUjOqYbrEjgJ+zNRlU2+n/b+JbCL/3akA9Gnnohk+Ge61GkwKU1bI2pCQd1mkfaJ21HOw6PLN22dqUZmxxnpDCVqJAPPSkDJWdZhLLLZeazPpKs+1KR9w80TIhgwWbN4hK0ppine3WTaj58wpIYhYFyxIKRWmDD7U=,iv:+87m/bRD27l1srwtEgOHFq9bEnz1CXy0xJi6B63WPlE=,tag:OAXDwy8qMeLlnemWfLn0Sw==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
