# yaml-language-server: $schema=https://kubernetesjsonschema.dev/v1.18.1-standalone-strict/secret-v1.json
apiVersion: v1
kind: Secret
metadata:
  name: external-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:fpzE/2J1nfu+5mFgYO9SVIJc00JGjmM0SQbD20yCLEuFGaAtlqLLCg==,iv:Bs+3U0m6YcWVoLTyoofwZpbgN/5onx2B0mooykgyqI8=,tag:VQAuRSUrKbbI82RparlK8w==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m23ymejrcl6ngxw3szegd0y9jczamudr4wuw9ql77g5h72xk64qsm6zvmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHZ2t5M2twRmpIQkJDVzdY
        VGtiOHd1amVVVDBWNVBYbmhSWVJXK3doalVBCnJqZnZINVFZQ1NPZnczQTJCeHZt
        M21RRzl4MWVjeHlhWk1qSlhoYmp6aWsKLS0tIGtRUERwZW5rakJwRlBpTXlCSnVp
        UEVmUUMraThhVnQ2emdHK252UHJQeG8Kw9jryuOdjTlkw0yw3Wt54NoDPJ8Cew27
        959tV9dceQDo+tWhnd6iOseHUq1B0/maejjPed+tteZJXCBOpFOdUA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T19:37:30Z"
  mac: ENC[AES256_GCM,data:GlqxXgwa/z7KWfXoES3slcqPsLT7NB9p72NM40TUfSBoSJ6BRRycyrsg0z96TNKToq19QlBsMA84mON3NjXREwXytndVCI2+6OEf3tc4PjaNAR2hplFHOsSFjfzz8fmoyJeCjgI/X23i4896w/UT0o1AFxDCrX6xpGhCMWmE9Js=,iv:PcKL8yJB953wtAKMmTlMNo17efDCugCMRBhmGY+210Y=,tag:kHvJ0+wcqlJETUoK5BmHiA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
