apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: adguard-home
  namespace: network
spec:
  chart:
    spec:
      chart: app-template
      version: 3.7.2
      reconcileStrategy: ChartVersion
      sourceRef:
        kind: HelmRepository
        namespace: flux-system
        name: bjw-s
  interval: 1h
  driftDetection:
    mode: enabled
  values:
    # Instead of using an init container, use a sidecar lifecycle hook
    controllers:
      adguard-home:
        type: statefulset
        replicas: 2
        annotations:
          configmap.reloader.stakater.com/reload: unbound
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.57@sha256:5c536c1e25f76693ae7ee5e64e8a029893e0f3f1778c8d2a9581383e60cfa9b9
              pullPolicy: IfNotPresent
            # Use a command wrapper to run setup first
            command:
              - sh
              - -c
              - >-
                mkdir -p /opt/adguardhome/work /opt/adguardhome/conf &&
                chmod -R 755 /opt/adguardhome/work /opt/adguardhome/conf &&
                exec /opt/adguardhome/AdGuardHome -s install -c /opt/adguardhome/conf/AdGuardHome.yaml -w /opt/adguardhome/work
            env:
              TZ: America/New_York
            probes:
              # Add a delay to allow setup to complete
              liveness: &probe
                enabled: true
                type: HTTP
                port: 3000
                path: /login.html
                spec:
                  initialDelaySeconds: 60
              readiness: *probe
              startup:
                <<: *probe
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
                  initialDelaySeconds: 60
            # Run as root to allow setup
            securityContext:
              readOnlyRootFilesystem: false
              runAsUser: 0
              runAsGroup: 0
              allowPrivilegeEscalation: true
          unbound:
            image:
              repository: ghcr.io/gabe565/unbound-cache
              tag: beta
              pullPolicy: Always
            env:
              TZ: America/New_York
            probes:
              liveness: &unbound_probe
                enabled: true
                type: TCP
                port: 5353
              readiness: *unbound_probe
              startup:
                <<: *unbound_probe
                spec:
                  failureThreshold: 30
                  periodSeconds: 5
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
        pod:
          priorityClassName: system-cluster-critical
          securityContext:
            fsGroup: 65534
            fsGroupChangePolicy: OnRootMismatch
            runAsNonRoot: false
          affinity:
            podAntiAffinity:
              preferredDuringSchedulingIgnoredDuringExecution:
                - weight: 1
                  podAffinityTerm:
                    topologyKey: kubernetes.io/hostname
                    labelSelector:
                      matchLabels:
                        app.kubernetes.io/name: adguard-home
                        app.kubernetes.io/component: adguard-home
        statefulset:
          volumeClaimTemplates:
            - name: data
              storageClass: longhorn
              accessMode: ReadWriteOnce
              size: 2Gi
              advancedMounts:
                app:
                  - path: /opt/adguardhome/conf
                    subPath: conf
                  - path: /opt/adguardhome/work
                    subPath: work
                unbound:
                  - path: /opt/unbound/data
                    subPath: unbound
      sync:
        containers:
          app:
            image:
              repository: ghcr.io/bakito/adguardhome-sync
              tag: alpine-v0.7.1@sha256:4409e1301375647bf177934c8441d79566d2c2557f0e0fa06a28fc6daeea65d4
              pullPolicy: IfNotPresent
            args: [run]
            env:
              - name: ORIGIN_URL
                value: http://adguard-home-origin:3000
              - name: ORIGIN_WEB_URL
                value: https://adguard-home.${SECRET_DOMAIN}
              - name: ORIGIN_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: &secret adguard-home-secret
                    key: SYNC_USERNAME
              - name: ORIGIN_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: SYNC_PASSWORD
              - name: REPLICA_URL
                value: http://adguard-home-replica:3000
              - name: REPLICA_WEB_URL
                value: https://replica.${SECRET_DOMAIN}
              - name: REPLICA_USERNAME
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: SYNC_USERNAME
              - name: REPLICA_PASSWORD
                valueFrom:
                  secretKeyRef:
                    name: *secret
                    key: SYNC_PASSWORD
              - name: REPLICA_AUTO_SETUP
                value: "true"
              - name: CRON
                value: "*/10 * * * *"
            securityContext:
              readOnlyRootFilesystem: true
              allowPrivilegeEscalation: false
              capabilities: {drop: [ALL]}
        pod:
          securityContext:
            runAsNonRoot: true

    service:
      adguard-home:
        controller: adguard-home
        ports:
          http:
            port: 3000
      sync:
        controller: sync
        ports:
          http:
            port: 8080
      origin: &origin-http
        controller: adguard-home
        extraSelectorLabels:
          apps.kubernetes.io/pod-index: "0"
        ports:
          http:
            port: 3000
      origin-dns: &origin-dns
        controller: adguard-home
        extraSelectorLabels:
          apps.kubernetes.io/pod-index: "0"
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 10.10.5.252
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

      replica:
        <<: *origin-http
        extraSelectorLabels:
          apps.kubernetes.io/pod-index: "1"
      replica-dns:
        <<: *origin-dns
        extraSelectorLabels:
          apps.kubernetes.io/pod-index: "1"
        type: LoadBalancer
        externalTrafficPolicy: Local
        loadBalancerIP: 10.10.5.253
        ports:
          dns-tcp:
            port: 53
            protocol: TCP
          dns-udp:
            port: 53
            protocol: UDP

    persistence:
      unbound:
        enabled: true
        type: configMap
        name: unbound
        advancedMounts:
          adguard-home:
            unbound:
              - path: /opt/unbound/etc/unbound/unbound.conf
                subPath: unbound.conf
      tmp:
        enabled: true
        type: emptyDir
        advancedMounts:
          adguard-home:
            unbound:
              - path: /opt/unbound/etc/unbound/dev
                subPath: dev
              - path: /opt/unbound/etc/unbound/var
                subPath: var

    ingress:
      app: &ingress
        className: internal
        annotations:
          external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
        hosts:
          - host: "{{ .Release.Name }}.${SECRET_DOMAIN}"
            paths:
              - path: /
                service:
                  identifier: adguard-home
                  port: http
      replica:
        <<: *ingress
        hosts:
          - host: replica.${SECRET_DOMAIN}
            paths:
              - path: /
                service:
                  identifier: replica
                  port: http