apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - helmrelease.yaml
  - externalsecret.yaml
configMapGenerator:
  - name: unbound
    options:
      disableNameSuffixHash: true
    files:
      - unbound.conf
