---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/external-secrets.io/externalsecret_v1beta1.json
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: adguard-home-secrets
  namespace: adguard-home
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword  # Must match your ClusterSecretStore name
  target:
    name: adguard-home-secrets  # The resulting Kubernetes Secret
    creationPolicy: Owner
    template:
      data:
        app_url: "{{ .APP_URL }}"
        sync_username: "{{ .SYNC_USERNAME }}"
        sync_password: "{{ .SYNC_PASSWORD }}"
        certificate_name: "{{ .CERTIFICATE_NAME }}"
  dataFrom:
    - extract:
        key: adguard-home  # The key in OnePassword holding these secrets