apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:xu80GG84yxkZ/cP0,iv:pRkjOIgLtFuoiF9ldbsENN7kUNii8iVHJk/uTsWU9zA=,tag:5EXF+wrm28SNRObmS/deoQ==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m23ymejrcl6ngxw3szegd0y9jczamudr4wuw9ql77g5h72xk64qsm6zvmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dHY2cXc4Vm1mcVYybWZt
        Z1FtanhDT3ZBQmlwbGUvVnhqSWlBOHJnYVZFCkNybVI2WW5xUUVKM0w0WHUyTDlk
        TXZQTmZ6ZnpYZlFYZmMwMXZ2d2hoR0UKLS0tIEs1b2djTy9yTzA5eVdkVThTQ3Fv
        ZmkzRjJuZWM3Y3EycEMwWnVPOGZnTWsKu90JXY4h8OPRYl8wiMblYB9o6ZfUPXlz
        1/P9MU5Uk/gyb8mpGaZIBO7Er2k0csqcFCbCk9cas0hT+XhoeE184A==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T19:37:30Z"
  mac: ENC[AES256_GCM,data:2GdlpF1Etmeb9vJ5dLipZWfUvXA0R78+MRza2TpQJ4jPdtNjr9ZE6iKDVbhIayMaDwJQniGtLIOPSEiPGrZW2Oy/bZqzw31Z3o8KwrqNcrByxugPbeEukqkK/M5luU+oApv5UeilxRr3tfUUTqEznrWOVX1Kg25iqE2zblkgdBA=,iv:8q8L5yTT+eP+sgEm/jAeNweZIWkIGou2WS4q0DQpKXw=,tag:WKE0aCWuZsC3PMpErF8njQ==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
