apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Fq3P0fZCmUcz5Py2,iv:5AjzNDWHs/w8T9aloGjuTQws27QJ6NRUQPSrz9Pb49w=,tag:44zgr4NlQPgdgZgn8Ny8qA==,type:str]
sops:
  kms: []
  gcp_kms: []
  azure_kv: []
  hc_vault: []
  age:
    - recipient: age1m23ymejrcl6ngxw3szegd0y9jczamudr4wuw9ql77g5h72xk64qsm6zvmh
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHT3piWlY5dnhhWVdGeGRj
        WmpTOUF1QzBRemlXY1cxLzAvTmxVYytWSzFRCjJJT3dHKy9vQjkvTnh1VjNha2pu
        Z2Q3bmQ4VStuTnpEZkk0bW1tUU5OY2cKLS0tIGw1T2tNYnlpVWsySnZkc0hSV1hJ
        YWpQLzZ2S0N3ZmtEbHYvTGRMVEdiMUUKLlZoWn0b9Ak0OldY6iUL16gMre4ahVpK
        kS92iw/OfjHDrqeb11rQzmNWa4TbB5F8WGYJetkSmwcKkKrd2nx/FA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-03-07T17:57:53Z"
  mac: ENC[AES256_GCM,data:jyjnUSFwIAbNl9pSQ3dWhV+ElWDavCyIT+3HWhIzCsepRTwKauSTZ2VkBeshumHOc/v3hG3lHqF1aDl09blSmoUSJZ/4X4Oh7/oLpPR+FBl2fvYlWOFwua/YlaPo6584++BnFFpqJgUTvZWgCA7Yh+x6MNeYaYVqkNb7w5R4YP8=,iv:ec4pidwD3gPJY/Ue7c1GdZXTsleY2cJH1KNFIWyLD4g=,tag:F/PSCFuKcZ2+uq9fQ4yGqA==,type:str]
  pgp: []
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.9.4
