# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.5.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.10.5.200"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-marsmaster-00"
    ipAddress: "10.10.5.170"
    installDisk: "/dev/nvme0n1"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de3b865124c5616da8084826167f8c0b0fbc9b905b146290db797024e84097fc
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "84:47:09:47:3c:a2"
        dhcp: false
        addresses:
          - "10.10.5.170/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
        vip:
          ip: "10.10.5.200"
  - hostname: "talos-marsmaster-01"
    ipAddress: "10.10.5.171"
    installDisk: "/dev/sdb"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/de3b865124c5616da8084826167f8c0b0fbc9b905b146290db797024e84097fc
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "54:bf:64:8e:7c:5d"
        dhcp: false
        addresses:
          - "10.10.5.171/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
        vip:
          ip: "10.10.5.200"

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

