# yaml-language-server: $schema=https://raw.githubusercontent.com/budimanjojo/talhelper/master/pkg/config/schemas/talconfig.json
---
clusterName: kubernetes

talosVersion: "${talosVersion}"
kubernetesVersion: "${kubernetesVersion}"

endpoint: https://10.10.5.200:6443
additionalApiServerCertSans: &sans
  - "127.0.0.1"
  - "10.10.5.200"
additionalMachineCertSans: *sans

clusterPodNets: ["10.42.0.0/16"]
clusterSvcNets: ["10.43.0.0/16"]

# Disable built-in CNI to use Cilium
cniConfig:
  name: none

nodes:
  - hostname: "talos-marsmaster-00"
    ipAddress: "10.10.5.170"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "76:99:6a:8f:ec:e0"
        dhcp: false
        addresses:
          - "10.10.5.170/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
        vip:
          ip: "10.10.5.200"
  - hostname: "talos-marsmaster-01"
    ipAddress: "10.10.5.171"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "c6:a4:41:b1:e3:ac"
        dhcp: false
        addresses:
          - "10.10.5.171/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
        vip:
          ip: "10.10.5.200"
  - hostname: "talos-marsmaster-02"
    ipAddress: "10.10.5.172"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: true
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "8e:31:03:44:c8:cf"
        dhcp: false
        addresses:
          - "10.10.5.172/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
        vip:
          ip: "10.10.5.200"
  - hostname: "talos-marsworker-00"
    ipAddress: "10.10.5.180"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "92:08:c3:4b:ac:ac"
        dhcp: false
        addresses:
          - "10.10.5.180/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
  - hostname: "talos-marsworker-01"
    ipAddress: "10.10.5.181"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "ca:e1:c3:e4:1f:64"
        dhcp: false
        addresses:
          - "10.10.5.181/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500
  - hostname: "talos-marsworker-02"
    ipAddress: "10.10.5.182"
    installDisk: "/dev/sda"
    machineSpec:
      secureboot: false
    talosImageURL: factory.talos.dev/installer/88d1f7a5c4f1d3aba7df787c448c1d3d008ed29cfb34af53fa0df4336a56040b
    controlPlane: false
    networkInterfaces:
      - deviceSelector:
          hardwareAddr: "f6:1b:ab:40:2c:47"
        dhcp: false
        addresses:
          - "10.10.5.182/21"
        routes:
          - network: "0.0.0.0/0"
            gateway: "10.10.0.1"
        mtu: 1500

# Global patches
patches:
  - "@./patches/global/machine-files.yaml"
  - "@./patches/global/machine-kubelet.yaml"
  - "@./patches/global/machine-network.yaml"
  - "@./patches/global/machine-sysctls.yaml"
  - "@./patches/global/machine-time.yaml"

# Controller patches
controlPlane:
  patches:
    - "@./patches/controller/admission-controller-patch.yaml"
    - "@./patches/controller/cluster.yaml"

