---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: adguard
  namespace: network
spec:
  secretName: tls-adguard
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: dns.tslamars.com
  dnsNames:
    - dns.tslamars.com
    - adguard.tslamars.com
  privateKey:
    rotationPolicy: Always