# yaml-language-server: $schema=https://raw.githubusercontent.com/bjw-s/helm-charts/main/charts/other/app-template/schemas/helmrelease-helm-v2.schema.json
---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app adguard-home
  namespace: network
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 3.7.1
      sourceRef:
        kind: HelmRepository
        name: bjw-s
        namespace: flux-system
  maxHistory: 2
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
      strategy: rollback
  uninstall:
    keepHistory: false
  values:
    controllers:
      adguard:
        containers:
          app:
            image:
              repository: adguard/adguardhome
              tag: v0.107.57@sha256:5c536c1e25f76693ae7ee5e64e8a029893e0f3f1778c8d2a9581383e60cfa9b9
              pullPolicy: IfNotPresent
            env:
              TZ: ${TIMEZONE}
            probes:
              liveness: &probe
                type: HTTP
                path: /login.html
                port: 80  # Match primary HTTP port
              readiness: *probe
              startup: *probe
            ports:  # Explicitly define container ports
              - containerPort: 80
                name: http
              - containerPort: 3000
                name: http-setup
              - containerPort: 53
                name: dns-tcp
                protocol: TCP
              - containerPort: 53
                name: dns-udp
                protocol: UDP
              - containerPort: 443
                name: dns-https
                protocol: TCP
              - containerPort: 853
                name: tls-tcp
                protocol: TCP

    service:
      app:
        nameOverride: *app
        controller: adguard
        ports:
          http:
            port: 80
            targetPort: http  # Maps to container port 80
          http-setup:
            port: 3000
            targetPort: http-setup  # Maps to container port 3000
      dns:
        controller: adguard
        type: LoadBalancer
        annotations:
          external-dns.alpha.kubernetes.io/hostname: dns.tslamars.com
          io.cilium/lb-ipam-ips: 10.10.5.250
        ports:
          dns-https:
            port: 443
            targetPort: dns-https
          dns-tcp:
            port: 53
            targetPort: dns-tcp
          dns-udp:
            port: 53
            targetPort: dns-udp
          tls-tcp:
            port: 853
            targetPort: tls-tcp
    ingress:
      app:
        className: internal
        hosts:
          - host: &host "adguard.tslamars.com"
            paths:
              - path: /
                service:
                  identifier: app
                  port: http  # Uses port 80
        tls:
          - hosts:
              - *host
    persistence:
      config:
        enabled: true
        existingClaim: adguard
        globalMounts:
          - path: /opt/adguardhome/conf
            subPath: conf
      work:
        enabled: true
        storageClass: longhorn
        accessMode: ReadWriteOnce
        size: 5Gi
        globalMounts:
          - path: /opt/adguardhome/work
            subPath: work
      tls:
        enabled: true
        type: secret
        name: tls-adguard
        globalMounts:
          - path: /opt/adguardhome/ssl/certs/
            readOnly: true