---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: jellyseerr
  namespace: media
spec:
  interval: 1h
  chartRef:
    kind: OCIRepository
    name: app-template
    namespace: flux-system
  values:
    controllers:
      jellyseerr:
        containers:
          app:
            image:
              repository: ghcr.io/jellyseerr/jellyseerr
              tag: latest
    persistence:
      config:
        type: nfs
        server: 10.69.70.10
        path: /volume1/.srv/.unifi-drive/kubernetes/.data/jellyseerr
        globalMounts:
          - path: /app/config
            readOnly: false
      config-cache:
        type: nfs
        server: 10.69.70.10
        path: /volume1/.srv/.unifi-drive/kubernetes/.data/jellyseerr
        globalMounts:
          - path: /app/config/cache
            readOnly: false
      config-logs:
        type: emptyDir
        globalMounts:
          - path: /app/config/logs
      tmp:
        type: emptyDir