provider: webhook

extraArgs:
  webhook-provider-url: http://localhost:8888

sidecars:
  - name: adguard-webhook
    image: 
      repository: ghcr.io/muhlba91/external-dns-provider-adguard
      tag: v8.0.0@sha256:1a7b12b3fef352626345653809716ada3d7569c930b1bf85c2e1b98e022ca9aa
    ports:
      - containerPort: 8888
        name: http
      - containerPort: 8080
        name: healthz
    livenessProbe:
      httpGet:
        path: /healthz
        port: healthz
      initialDelaySeconds: 10
      timeoutSeconds: 5
    readinessProbe:
      httpGet:
        path: /healthz
        port: healthz
      initialDelaySeconds: 10
      timeoutSeconds: 5
    env:
      - name: LOG_LEVEL
        value: debug
      - name: ADGUARD_URL
        valueFrom:
          secretKeyRef:
            name: &secret internal-external-dns-secret
            key: ADGUARD_URL
      - name: ADGUARD_USER
        valueFrom:
          secretKeyRef:
            name: &secret internal-external-dns-secret
            key: ADGUARD_USER
      - name: ADGUARD_PASSWORD
        valueFrom:
          secretKeyRef:
            name: &secret internal-external-dns-secret
            key: ADGUARD_PASSWORD
      - name: DRY_RUN
        value: "false"
