---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: &app internal-external-dns
spec:
  interval: 1h
  chart:
    spec:
      chart: external-dns
      version: 1.15.2
      sourceRef:
        kind: HelmRepository
        name: external-dns
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    fullnameOverride: *app
    # logLevel: debug
    provider:
      name: webhook
      webhook:
        image:
          repository: ghcr.io/kashalls/external-dns-unifi-webhook
          tag: v0.4.2@sha256:c8eb92acd71170347b77096cbda0708fd573b55334274cbbc577dee051c7abd7
        env:
          - name: UNIFI_HOST
            value: https://10.69.1.1
          - name: UNIFI_API_KEY
            valueFrom:
              secretKeyRef:
                name: &secret internal-external-dns-secret
                key: UNIFI_API_KEY
          # - name: LOG_LEVEL
          #   value: "debug"
        livenessProbe:
          httpGet:
            path: /healthz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /readyz
            port: http-webhook
          initialDelaySeconds: 10
          timeoutSeconds: 5
    extraArgs:
      - --ignore-ingress-tls-spec
    triggerLoopOnEvent: true
    policy: sync
    sources: ["ingress", "service"]
    txtOwnerId: main
    txtPrefix: k8s.main.
    domainFilters: ["tslamars.com"]
    serviceMonitor:
      enabled: true
    podAnnotations:
      secret.reloader.stakater.com/reload: *secret
    sidecars:
      - name: adguard-webhook
        image: 
          repository: ghcr.io/muhlba91/external-dns-provider-adguard
          tag: v8.0.0@sha256:1a7b12b3fef352626345653809716ada3d7569c930b1bf85c2e1b98e022ca9aa
        ports:
          - containerPort: 8888
            name: http
          - containerPort: 8080
            name: healthz
        livenessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        readinessProbe:
          httpGet:
            path: /healthz
            port: healthz
          initialDelaySeconds: 10
          timeoutSeconds: 5
        env:
          - name: LOG_LEVEL
            value: debug
          - name: ADGUARD_URL
            valueFrom:
              secretKeyRef:
                name: &secret internal-external-dns-secret
                key: url
          - name: ADGUARD_USER
            valueFrom:
              secretKeyRef:
                name: &secret internal-external-dns-secret
                key: user
          - name: ADGUARD_PASSWORD
            valueFrom:
              secretKeyRef:
                name: &secret internal-external-dns-secret
                key: password
          - name: DRY_RUN
            value: "false"