---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system  # Ensure this matches your intended namespace
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultSettings:
      # Prevent Longhorn from using /var/lib/longhorn on unlabeled nodes
      createDefaultDiskLabeledNodes: false
      defaultDataLocality: true
      replicaAutoBalance: true
      storageMinimalAvailablePercentage: 1
      storageReservedPercentageForDefaultDisk: 10
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      orphanAutoDeletion: true
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      # Optional: Restrict to labeled nodes (if needed)
      defaultNodeSelector:
        longhorn.io/managed: "true"  # Matches nodes labeled with longhorn.io/managed=true
    longhornManager:
      nodeSelector:
        longhorn.io/managed: "true"  # Ensures managers run on these nodes
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: false
    metrics:
      serviceMonitor:
        enabled: true