---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  labels:
    pod-security.kubernetes.io/enforce: privileged
    pod-security.kubernetes.io/enforce-version: v1.28
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    csi:
      #attacherReplicaCount: 3
      #provisionerReplicaCount: 3
      # resizerReplicaCount: *replicas
      # snapshotterReplicaCount: *replicas
    # persistence:
    #   defaultClassReplicaCount: 1
    defaultSettings:
      createDefaultDiskLabeledNodes: true
      #defaultDiskLabel: "longhorn-disk=true"
      #default-data-path: "/var/mnt/data"
      #nodeSelector:
      #longhorn-disk: "true"
      defaultDataLocality: true
      replica-auto-balance: "best-effort"
      #replicaAutoBalance: true
      storageMinimalAvailablePercentage: 1
      storageReservedPercentageForDefaultDisk: 5
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      orphanAutoDeletion: true
      longhornStorageClass:
      reclaimPolicy: Delete
      allowVolumeExpansion: true
      parameters:
        numberOfReplicas: "3"
        staleReplicaTimeout: "30"
        fsType: "ext4"
    # longhornUI:
    #   replicas: *replicas
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.tslamars.com"
      host: "longhorn.tslamars.com"
      tls: false
    metrics:
      serviceMonitor:
        enabled: true
