---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: storage
spec:
  interval: 30m
  chart:
    spec:
      chart: longhorn
      version: 1.8.1
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      strategy: rollback
      retries: 3
  values:
    defaultSettings:
      createDefaultDiskLabeledNodes: false
      defaultDataLocality: true
      replicaAutoBalance: true
      storageMinimalAvailablePercentage: 1
      storageReservedPercentageForDefaultDisk: 10
      defaultLonghornStaticStorageClass: longhorn
      nodeDownPodDeletionPolicy: delete-both-statefulset-and-deployment-pod
      concurrentAutomaticEngineUpgradePerNodeLimit: 3
      orphanAutoDeletion: true
      # Enable SPDK for block device support
      enableSPDK: true
    persistence:
      defaultClass: true
      defaultClassReplicaCount: 1
      defaultNodeSelector:
        longhorn.io/managed: "true"
    longhornManager:
      nodeSelector:
        longhorn.io/managed: "true"
      securityContext:
        privileged: true
      volumeMounts:
        - mountPath: "/dev"
          name: host-dev
      volumes:
        - name: host-dev
          hostPath:
            path: "/dev"
            type: Directory
    ingress:
      enabled: true
      ingressClassName: internal
      annotations:
        external-dns.alpha.kubernetes.io/target: "internal.${SECRET_DOMAIN}"
      host: "longhorn.${SECRET_DOMAIN}"
      tls: false
    metrics:
      serviceMonitor:
        enabled: true