---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/cert-manager.io/certificate_v1.json
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: tslamars-com-production
spec:
  secretName: tslamars-com-production-tls
  issuerRef:
    name: letsencrypt-production
    kind: ClusterIssuer
  commonName: tslamars.com
  dnsNames: ["tslamars.com", "*.tslamars.com"]
