---
originRequest:
  originServerName: external.tslamars.com

ingress:
  - hostname: tslamars.com
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - hostname: "*.tslamars.com"
    service: https://external-ingress-nginx-controller.network.svc.cluster.local:443
  - service: http_status:404
